# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='item',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='first_app.Guest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='wisher',
            field=models.ManyToManyField(related_name='wish', to='first_app.Guest'),
        ),
    ]
